MAX_UPLOAD_FILES: int = 7
MAX_FILE_SIZE_MB: int = 50
MAX_FILE_SIZE_BYTES: int = MAX_FILE_SIZE_MB * 1024 * 1024
MAX_PAPERS_PER_SESSION: int = 20
MAX_SESSIONS: int = 50

MAX_PARALLEL_PAPERS: int = 3
MEMORY_PRESSURE_THRESHOLD: float = 0.75
PAPER_PROCESSING_TIMEOUT_SECONDS: int = 600

EMBEDDING_MODEL_NAME: str = "all-MiniLM-L6-v2"
EMBEDDING_DIMENSIONS: int = 384
EMBEDDING_BATCH_SIZE: int = 64

HAVF_HIGH_THRESHOLD: float = 0.85
HAVF_MEDIUM_THRESHOLD: float = 0.65
HAVF_CROSS_ENCODER_THRESHOLD: float = 0.75
HAVF_SHORT_SENTENCE_WORDS: int = 5

CROSS_ENCODER_MODEL: str = "cross-encoder/ms-marco-MiniLM-L-6-v2"

MAX_CONTEXT_TOKENS: int = 6_000
MAX_QUERY_TOKENS: int = 512
MIN_PARAGRAPHS_PER_PAPER: int = 1
HISTORY_TOKEN_BUDGET: int = 2_000
SYSTEM_PROMPT_TOKEN_BUDGET: int = 500
RESPONSE_TOKEN_BUDGET: int = 1_000
MAX_CONVERSATION_TURNS: int = 5

CHUNK_TARGET_TOKENS: int = 512
CHUNK_MAX_TOKENS: int = 1024

FAISS_TOP_K_PER_PAPER: int = 4
FAISS_INDEX_DIR: str = "data/faiss_indexes"
FAISS_MAX_VECTORS: int = 500_000

LLM_TIMEOUT_SECONDS: int = 30
LLM_MAX_RETRIES: int = 2
LLM_RETRY_DELAY_BASE: float = 2.0
LLM_TEMPERATURE: float = 0.3

UPLOADS_DIR: str = "data/uploads"
EXPORTS_DIR: str = "data/exports"

MIN_DISK_SPACE_MB: int = 500
MAX_EXPORT_FILE_SIZE_MB: int = 100
MAX_WS_CONNECTIONS_PER_SESSION: int = 10

COMPARISON_TOKEN_BUDGET_PER_PAPER: int = 3_000

WS_PAPER_PROGRESS: str = "paper_progress"
WS_PAPER_COMPLETE: str = "paper_complete"
WS_PAPER_ERROR: str = "paper_error"
WS_PROCESSING_DONE: str = "processing_done"

