"""TraceLit — Word (DOCX) Exporter.

Generates styled Word documents for:
- Literature reviews (multi-paper analysis)
- Session chat history
Uses python-docx for document generation.
"""

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from loguru import logger


def generate_literature_review_docx(
    title: str,
    review_text: str,
    papers: List[Dict[str, Any]],
    output_path: Optional[str] = None,
) -> bytes:
    """Generate a Word document for a literature review.

    Args:
        title: Review title.
        review_text: LLM-generated literature review text with citations.
        papers: List of paper metadata dicts (id, title, authors, year).
        output_path: Optional file path to save to. If None, returns bytes.

    Returns:
        Document bytes (DOCX format).
    """
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # -- Title --
    title_para = doc.add_heading(title or "Literature Review", level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # -- Metadata --
    meta_para = doc.add_paragraph()
    meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta_para.add_run(f"Generated by TraceLit — {datetime.now().strftime('%B %d, %Y')}")
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(128, 128, 128)

    doc.add_paragraph()  # spacer

    # -- Review body --
    # Split into paragraphs and handle section headers (lines starting with ##)
    review_lines = review_text.strip().split("\n")

    for line in review_lines:
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph()
            continue

        # Markdown-style headers
        if stripped.startswith("### "):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith("## "):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith("# "):
            doc.add_heading(stripped[2:], level=1)
        elif stripped.startswith("- ") or stripped.startswith("* "):
            # Bullet point
            doc.add_paragraph(stripped[2:], style="List Bullet")
        else:
            # Regular paragraph — handle inline citations [P#]
            para = doc.add_paragraph()
            _add_text_with_citations(para, stripped)

    # -- References section --
    doc.add_page_break()
    doc.add_heading("References", level=1)

    for i, paper in enumerate(papers, 1):
        authors = paper.get("authors", [])
        if isinstance(authors, str):
            try:
                authors = json.loads(authors)
            except (json.JSONDecodeError, TypeError):
                authors = [authors]

        author_str = ", ".join(authors[:3])
        if len(authors) > 3:
            author_str += " et al."

        year = paper.get("year", "n.d.")
        title_str = paper.get("title", "Untitled")

        ref_para = doc.add_paragraph(style="List Number")
        ref_para.add_run(f"{author_str} ({year}). ").bold = False
        ref_para.add_run(f"{title_str}").italic = True

    # -- Output --
    if output_path:
        doc.save(output_path)
        logger.info("Literature review DOCX saved to {}", output_path)

    # Always return bytes
    from io import BytesIO
    buffer = BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def generate_session_docx(
    session_id: str,
    session_title: str,
    messages: List[Dict[str, Any]],
    papers: List[Dict[str, Any]],
    output_path: Optional[str] = None,
) -> bytes:
    """Generate a Word document of a chat session.

    Args:
        session_id: Session identifier.
        session_title: Human-readable session title.
        messages: List of message dicts with role and content.
        papers: List of paper metadata dicts.
        output_path: Optional file path to save to.

    Returns:
        Document bytes (DOCX format).
    """
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # -- Title --
    title_para = doc.add_heading(session_title or "Chat Session", level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta_para = doc.add_paragraph()
    meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta_para.add_run(f"TraceLit Session — {datetime.now().strftime('%B %d, %Y %H:%M')}")
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(128, 128, 128)

    # -- Papers used --
    if papers:
        doc.add_heading("Papers Referenced", level=2)
        for paper in papers:
            p_title = paper.get("title", "Untitled")
            doc.add_paragraph(f"• {p_title}", style="List Bullet")

    doc.add_paragraph()  # spacer

    # -- Messages --
    doc.add_heading("Conversation", level=2)

    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "")

        if role == "user":
            para = doc.add_paragraph()
            run = para.add_run("You: ")
            run.bold = True
            run.font.color.rgb = RGBColor(0, 90, 158)
            _add_text_with_citations(para, content)
        else:
            para = doc.add_paragraph()
            run = para.add_run("TraceLit: ")
            run.bold = True
            run.font.color.rgb = RGBColor(0, 128, 64)
            _add_text_with_citations(para, content)

        doc.add_paragraph()  # spacer between messages

    # -- Output --
    if output_path:
        doc.save(output_path)
        logger.info("Session DOCX saved to {}", output_path)

    from io import BytesIO
    buffer = BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def _add_text_with_citations(paragraph, text: str) -> None:
    """Add text to a paragraph, styling [P#] citations as superscripts."""
    from docx.shared import Pt, RGBColor

    pattern = re.compile(r"(\[P\d+\])")
    parts = pattern.split(text)

    for part in parts:
        if pattern.match(part):
            run = paragraph.add_run(part)
            run.font.size = Pt(8)
            run.font.superscript = True
            run.font.color.rgb = RGBColor(0, 102, 204)
        else:
            paragraph.add_run(part)
